### ISSUE TITLE
 error while loading shared libraries: liblz4.so.1

### ISSUE THREAD

**Issue by wheatwill** [tlemane/kmtricks#18]
Hello,

I installed kmtricks with conda, and I got the error when I tried to run it：
kmtricks: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory
here is my systerm kmtricks：
————————————————
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Thanks for your help!

**Comment by tlemane** [comment]
Hello,

I think I made a mistake when building the package. I just uploaded a new one, it should be fixed now.

**Comment by wheatwill** [comment]
Hi，
Yes! I use `conda install -c conda-forge -c tlemane kmtricks=1.2.1`reinstalled it, and it work now.
while the default version by conda is 1.1.1.
