### ISSUE TITLE
make test failed la deuxième fois

### ISSUE THREAD

**Issue by gcollet** [tlemane/kmtricks#2]
J'ai fait une modif, j'ai relancé `make test` pour voir et ça a fail. Bon ok mais j'ai comme un doute.

Du coup, j'ai remis le répertoire test tout propre comme quand j'ai cloné le dépôt et j'ai enlevé ma modif.
Je lance une première fois make test -> pass
Je lance une deuxième fois make test (sans rien changer) -> fail

Y a un truc bizarre :-)

**Comment by tlemane** [comment]
Hello,

Le script de test n'effaçait pas les fichiers du test précédent. Ça posait problème parce que les fichiers dans .run_test/storage/kmers_partitions sont ouverts en mode append.                                                                    

C'est corrigé.
Merci
