### ISSUE TITLE
Specify python version in Conda recipe

### ISSUE THREAD

**Issue by kbseah** [tlemane/kmtricks#7]
I installed kmtricks v0.0.2 with conda. Running `kmtricks.py` with python < 3.6 results in the following error message:
```
  File "/ebio/abt2_projects/ag-swart-loxodes/envs/kmtricks/bin/kmtricks.py", line 109
    self.global_parser: argparse.ArgumentParser = None
                      ^
SyntaxError: invalid syntax
```

It appears that the version check in lines 40-42 of `kmtricks.py` isn't used because it's not enclosed in the main code block.

Perhaps the python version could be included in the Conda recipe? I've gotten it to work now and look forward to trying out the pipeline.

**Comment by tlemane** [comment]
Hi,

Thank you for reporting this. The minimal python version is now included in the conda recipe.
