### ISSUE TITLE
Possibility to output raw counts ?

### ISSUE THREAD

**Issue by hl-xue** [tlemane/kmtricks#9]
Hello,

Thanks for developping this nice tool !
I found the output counts are scaled into 0-255 by default, and I was wondering if there is some way to have the raw counts as output without scaling ? 

Thanks and best wishes.

**Comment by tlemane** [comment]
Hello,

Thanks for trying kmtricks!
Yes by default the maximum is 255 to use only one byte per count. You can change this value using `--max-count N`.

**Comment by hl-xue** [comment]
Thanks for reply. So the N is a value ? So in case I don't know the maximum of the count and I would like to put a very big N, is there any limitation for this value ?

**Comment by tlemane** [comment]
Yes kmtricks can use 8, 16 or 32-bit unsigned integer to store counts. So the maximum is 2<sup>32</sup>-1.

**Comment by hl-xue** [comment]
OK, thanks a lot !
Best wishes.
